# Generated by Django 3.2.8 on 2021-11-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='busNumber',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='bus',
            name='countPlace',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat_no',
            field=models.IntegerField(),
        ),
    ]
