# Generated by Django 3.2.8 on 2021-10-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='scheduledArrival',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='scheduledDeparture',
            field=models.DateField(),
        ),
    ]
