# Generated by Django 3.2.8 on 2021-10-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_auto_20211020_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='scheduledArrival',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='scheduledDeparture',
            field=models.DateTimeField(),
        ),
    ]
