# Generated by Django 3.2.8 on 2021-10-21 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_auto_20211021_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.bus'),
        ),
    ]
