# Generated by Django 3.2.8 on 2021-11-30 12:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_auto_20211130_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2021, 11, 30, 12, 38, 33, 783594, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='gender',
            field=models.CharField(choices=[('М', 'М'), ('Ж', 'Ж')], default='', max_length=20),
        ),
    ]
