# Generated by Django 3.2.8 on 2021-12-01 20:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0004_auto_20211130_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkcar',
            name='address',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2021, 12, 1, 20, 54, 33, 322557, tzinfo=utc)),
        ),
    ]
