# Generated by Django 3.2.8 on 2021-12-01 21:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0005_auto_20211201_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkcar',
            name='address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='parkcar',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='parkcar',
            name='parkName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2021, 12, 1, 21, 0, 1, 834865, tzinfo=utc)),
        ),
    ]
