# Generated by Django 3.2.8 on 2021-10-31 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0005_flight_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='flight',
        ),
        migrations.CreateModel(
            name='TicketFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.flight')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flight.ticket')),
            ],
        ),
    ]
