# Generated by Django 3.2.8 on 2021-10-31 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0006_auto_20211031_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketflight',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=10),
            preserve_default=False,
        ),
    ]
