# Generated by Django 3.2.8 on 2021-10-31 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0006_auto_20211031_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='flight',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='flight.flight'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TicketFlight',
        ),
    ]
