# Generated by Django 3.2.8 on 2021-12-03 15:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0007_auto_20211203_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='ticket',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='./'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2021, 12, 3, 15, 32, 26, 776132, tzinfo=utc)),
        ),
    ]
