# Generated by Django 3.2.8 on 2021-10-31 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0007_auto_20211031_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
