# Generated by Django 3.2.8 on 2021-11-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0008_alter_flight_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
