# Generated by Django 3.2.8 on 2021-12-13 19:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0008_auto_20211203_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2021, 12, 13, 19, 19, 20, 128656, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='./qr_code'),
        ),
    ]
