# Generated by Django 3.2.8 on 2021-12-13 22:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0009_auto_20211213_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2021, 12, 13, 22, 6, 24, 321959, tzinfo=utc)),
        ),
    ]
