# Generated by Django 3.2.8 on 2021-12-13 22:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0010_alter_ticket_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2021, 12, 13, 22, 16, 16, 489278, tzinfo=utc)),
        ),
    ]
