# Generated by Django 3.2.8 on 2021-12-14 15:47

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_managers'),
        ('flight', '0015_alter_ticket_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.inspector'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2021, 12, 14, 15, 47, 12, 915358, tzinfo=utc)),
        ),
    ]
