# Generated by Django 3.2.8 on 2022-01-09 19:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0016_auto_20211214_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2022, 1, 9, 19, 4, 40, 189612, tzinfo=utc)),
        ),
    ]
