# Generated by Django 3.2.8 on 2022-01-28 13:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0017_auto_20220109_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2022, 1, 28, 13, 17, 44, 14485, tzinfo=utc)),
        ),
    ]
