# Generated by Django 3.2.8 on 2022-02-01 16:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0018_alter_ticket_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2022, 2, 1, 16, 35, 29, 649424, tzinfo=utc)),
        ),
    ]
